<!doctype html>
<html lang="en">
{include file="head.tpl"}
<body>
    {include file="navigation.tpl"}
    <article>
        <h1>North Pole</h1>
        <p>The North Pole, also known as the Geographic North Pole or Terrestrial North Pole, is (subject to the caveats explained below) defined as the point in the Northern Hemisphere where the Earth's axis of rotation meets its surface.</p>
        <p>The North Pole is the northernmost point on the Earth, lying diametrically opposite the South Pole. It defines geodetic latitude 90° North, as well as the direction of true north. At the North Pole all directions point south; all lines of longitude converge there, so its longitude can be defined as any degree value. Along tight latitude circles, counterclockwise is east and clockwise is west. The North Pole is at the center of the Northern Hemisphere. The nearest land is usually said to be Kaffeklubben Island, off the northern coast of Greenland about 700 km (430 mi) away, though some perhaps semi-permanent gravel banks lie slightly closer. The nearest permanently inhabited place is Alert in the Qikiqtaaluk Region, Nunavut, Canada, which is located 817 km (508 mi) from the Pole.</p>
        <p>While the South Pole lies on a continental land mass, the North Pole is located in the middle of the Arctic Ocean amid waters that are almost permanently covered with constantly shifting sea ice. The sea depth at the North Pole has been measured at 4,261 m (13,980 ft) by the Russian Mir submersible in 2007[1] and at 4,087 m (13,409 ft) by USS Nautilus in 1958.[2][3] This makes it impractical to construct a permanent station at the North Pole (unlike the South Pole). However, the Soviet Union, and later Russia, constructed a number of manned drifting stations on a generally annual basis since 1937, some of which have passed over or very close to the Pole. Since 2002, the Russians have also annually established a base, Barneo, close to the Pole. This operates for a few weeks during early spring. Studies in the 2000s predicted that the North Pole may become seasonally ice-free because of Arctic ice shrinkage, with timescales varying from 2016[4][5] to the late 21st century or later.</p>
        <p>Attempts to reach the North Pole began in the late 19th century, with the record for "Farthest North" being surpassed on numerous occasions. The first undisputed expedition to reach the North Pole was that of the airship Norge, which overflew the area in 1926 with 16 men on board, including expedition leader Roald Amundsen. Three prior expeditions – led by Frederick Cook (1908, land), Robert Peary (1909, land) and Richard E. Byrd (1926, aerial) – were once also accepted as having reached the Pole. However, in each case later analysis of expedition data has cast doubt upon the accuracy of their claims.</p>
        {if $is_user_logged_in eq true}
        <h2>Lofoten</h2>
        <img src="https://upload.wikimedia.org/wikipedia/commons/1/18/Reine-3.jpg" alt="Lofoten"/>
        <p>Lofoten (Norwegian pronunciation: [ˈlùːfuːtn̩]) is an archipelago and a traditional district in the county of Nordland, Norway. Lofoten is known for a distinctive scenery with dramatic mountains and peaks, open sea and sheltered bays, beaches and untouched lands. Its largest town, Leknes, lies approximately 169 km inside the Arctic Circle, or approximately 2,420 km away from the North Pole, thus making Lofoten one of the world's northernmost populated regions. Though lying within the Arctic Circle, the archipelago experiences one of the world's largest elevated temperature anomalies relative to its high latitude.</p>
        {/if}
    </article>
</body>